---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    data_bags_path: 'test/integration/data_bags'
    roles_path: 'test/integration/roles'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - role[my_apache]
    attributes:
