---
driver:
  name: docker
  use_sudo: false
  #volume: ['/var/run/docker.sock:/var/run/docker.sock']
  privileged: true
  forward: 80

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: centos-7.1
  driver:
#    image: centos:7
#    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget

suites:
  - name: default
    driver:
      publish_all: true
      instance_name: first_cluster
    run_list:
      - recipe[test_apache::default]
    #attributes:
  - name: not_default
    driver:
      links: "first_cluster:first_cluster"
    run_list:
      - recipe[test_glibc::default]
    #attributes:
