---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids: <%= ENV['SECURITY_GROUP_IDS'] %>
  region: us-west-2
  availability_zone: b
  require_chef_omnibus: true
  subnet_id: <%= ENV['SUBNET_ID'] %>
  #iam_profile_name: chef-client
  instance_type: t2.micro
  associate_public_ip: true
  interface: public

transport:
  ssh_key: <%= ENV['SSH_KEY_FULL_PATH'] %>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-c94856a8

suites:
  - name: chef
    data_bags_path: 'test/integration/data_bags'
    roles_path: 'test/integration/roles'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - role[my_apache]
    attributes:
      citadel:
        access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['SECRET_ACCESS_KEY'] %>