name 'test_apache'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test_apache'
long_description 'Installs/Configures test_apache'
version '0.1.0'

depends 'apache2'
depends 'citadel'
